aixplain/aiXplain

- .env.example
- aixplain/__init__.py
- aixplain/factories/pipeline_factory.py
- aixplain/modules/pipeline.py
- aixplain/utils/config.py
- tests/pipeline_test.py
Instead of having to define `BACKEND_URL`, `MODELS_RUN_URL` and `PIPELINES_RUN_URL`, now we only need to define `AIXPLAIN_ENV` to set the desired environment (dev, test or platform).
Task: M-4576168247
> Remove PIPELINES_RUN_URL environment variable

- aixplain/decorators/__init__.py
- aixplain/factories/finetune_factory.py
- docs/user/user_doc.md
Remove decorator from FinetuneFactory, create __init__.py file inside the decorator folder, and update user_doc, including Colab links to dataset and corpus onboarding.
While running pip install from github repo inside Colab:
```bash
!pip install git+https://github.com/aixplain/aiXplain.git
```
and then importing the dependencies, I'm getting the following error:
By removing the decorator from FinetuneFactory and creating __init__.py file, we should fix this problem. Then, we can update the Colab to install the package using the above command.
Task: M-4813362133
> Remove unused decorator import and add Colab links in user docs

- docs/user/user_doc.md
- tests/functional/finetune/data/finetune_test_run_data.json
> Update user docs and add FineTune Search and LLM functional tests

- docs/user/user_doc.md
- tests/functional/finetune/data/finetune_test_run_data.json
- tests/functional/finetune/finetune_functional_test.py
Removing problematic fine-tuning test due to AWS rate-limiting until this problem is fixed.
> Removing problematic finetuning test

- aixplain/modules/finetune/hyperparameters.py
- tests/functional/finetune/finetune_functional_test.py
> Add learning rate scheduler and early stopping to FineTune LLMs

- tests/functional/finetune/data/finetune_test_cost_estimation.json
- tests/functional/finetune/data/finetune_test_end2end.json
- tests/functional/finetune/finetune_functional_test.py
> Add Finetuner cost estimation functional tests

- docs/user/user_doc.md
I updated the Hugging Face onboarding and self-onboarding feature documentation to "under maintentance" as per Nur's request.
> Updated onboarding docs

- aixplain/factories/pipeline_factory.py
- pyproject.toml
> Add input/output to PipelineFactory and use api_key from parameter

- README.md
Remove the `main.html` page from the URL.
> Fix the API reference documentation link

- aixplain/factories/agent_factory/__init__.py
- aixplain/factories/agent_factory/utils.py
- aixplain/modules/agent/tool/model_tool.py
- aixplain/modules/agent/tool/pipeline_tool.py
- tests/functional/agent/agent_functional_test.py
- tests/functional/agent/data/agent_test_end2end.json
> Add agents functional tests

- aixplain/factories/agent_factory/__init__.py
- tests/functional/agent/agent_functional_test.py
Decreasing the number of imports to generate an agent:
```python
from aixplain.factories import AgentFactory
from aixplain.enums import Function, Supplier
translation_pipeline_tool = AgentFactory.create_pipeline_tool(
description="English TTs Pipeline",
pipeline="66829cbad7b8325606297f81"
)
speech_synthesis_tool = AgentFactory.create_model_tool(
function=Function.SPEECH_SYNTHESIS,
supplier=Supplier.GOOGLE
)
ner_tool = AgentFactory.create_model_tool(
function=Function.NAMED_ENTITY_RECOGNITION,
supplier=Supplier.MICROSOFT
)
agent = AgentFactory.create(
name="Test Agent Colab 2024_07_26",
tools=[
speech_synthesis_tool,
ner_tool,
translation_pipeline_tool
],
description="Test Agent Description",
llm_id="6646261c6eb563165658bbb1" # GPT 4o
)
```
> create model/pipeline tools from AgentFactory

- aixplain/modules/agent/__init__.py
- tests/functional/agent/agent_functional_test.py
```python
from aixplain.enums import Function, Supplier
from aixplain.factories import AgentFactory
from aixplain.modules.agent import ModelTool, PipelineTool
agent = AgentFactory.create(
name="Test Agent 23423",
tools=[
ModelTool(
function=Function.SPEECH_RECOGNITION,
supplier=Supplier.MICROSOFT,
),
ModelTool(
function=Function.TRANSLATION,
supplier=Supplier.MICROSOFT
)
],
description="Test Agent Description",
supplier="aiXplain",
version="1.0.0",
llm_id="6646261c6eb563165658bbb1",
)
response = agent.run(
query="Translate the English texts within the links to Portuguese:",
content_inputs=[
"https://aixplain-platform-assets.s3.amazonaws.com/samples/en/CPAC1x2.txt",
"https://aixplain-platform-assets.s3.amazonaws.com/samples/en/bestofyou.txt"
]
)
```
> Content inputs to be processed according to the query.

- aixplain/factories/model_factory.py
- aixplain/modules/model/__init__.py
- tests/functional/general_assets/asset_functional_test.py
- tests/unit/model_test.py
Please note I'm not sure about the test. Let me know if there's anything I can improve.
> Added input and output attributes to model

- aixplain/modules/agent/__init__.py
- tests/functional/agent/agent_functional_test.py
- tests/functional/team_agent/team_agent_functional_test.py
> Fix agent and team agent functional tests

- aixplain/factories/pipeline_factory/utils.py
- aixplain/modules/pipeline/designer/base.py
- aixplain/modules/pipeline/designer/pipeline.py
- aixplain/modules/pipeline/designer/utils.py
- tests/unit/designer_unit_test.py
This PR will handle the population of below the prompt variables automatically. And their validation as well.
```
from aixplain.enums import DataType
from aixplain.factories import PipelineFactory
from aixplain.modules import Pipeline
pipeline = PipelineFactory.init("Simple RAG")
question_input = pipeline.input()
question_input.label = "QuestionInput"
search_node = pipeline.search(asset_id="66fb68b6c2d6534d5a3fe1a8")
OPENAI_GPT4O_MINI_ASSET = "669a63646eb56306647e1091"
llm_node = pipeline.text_generation(asset_id=OPENAI_GPT4O_MINI_ASSET)
llm_node.inputs.prompt = """Based on the context, answer the question.
Context:
{{context_data}}
Question:
{{question_data}}
Answer:"""
question_input.outputs.input.link(search_node.inputs.text)
question_input.outputs.input.link(llm_node.inputs.question_da …
```
> BUG-233 Prompt variables are now populated and validated automatically

- aixplain/enums/data_type.py
- aixplain/factories/model_factory/__init__.py
- aixplain/factories/model_factory/utils.py
- aixplain/modules/model/utility_model.py
- tests/functional/model/run_utility_model_test.py
- tests/unit/model_test.py
- tests/unit/utility_test.py
```python
from aixplain.factories import ModelFactory
from aixplain.modules.model.utility_model import UtilityModelInput
from aixplain.enums import DataType
inputs = [
UtilityModelInput(name="inputA", description="input A is the only input", type=DataType.TEXT),
]
code = "def main(inputA):\n\treturn inputA"
output_description = "An example is 'test'"
utility_model = ModelFactory.create_utility_model(
name="test_script",
description="This is a test script",
inputs=inputs,
code=code,
output_description=output_description,
)
response = utility_model.run(data={"inputA": "test"})
assert response.status == "SUCCESS"
assert response.data == "test"
utility_model.code = "def main(inputA):\n\treturn 5"
utility_model.update()
response = utility_model.run(data={"inputA": "test"})
assert …
```
> ENG-1110: Onboard Utilities

- .gitignore
- aixplain/modules/agent/__init__.py
- aixplain/modules/model/utility_model.py
- aixplain/modules/pipeline/asset.py
- aixplain/modules/team_agent/__init__.py
- tests/unit/agent_test.py
- tests/unit/pipeline_test.py
- tests/unit/utility_test.py
I need a first review to continue this task.
> ENG-1245: transition from update to save

- aixplain/factories/pipeline_factory/utils.py
- aixplain/modules/pipeline/designer/__init__.py
- aixplain/modules/pipeline/designer/nodes.py
Added `BareReconstructor` and `BareSegmentor` implementations in place to make them included in pipeline population. Below the code snippet populated and run successfully.
```
from aixplain.factories import PipelineFactory
pipeline = PipelineFactory.get("65f33fec4b3136f9eeae5511")
pipeline.run("https://homepage.ntu.edu.tw/~karchung/miniconversations/mc1.mp3")
```
> ENG-1289: Enabled reconstructor and segmentor designer nodes when pipeline fetched

- aixplain/modules/model/index_model.py
- aixplain/modules/model/record.py
- tests/functional/model/run_model_test.py
- tests/unit/index_model_test.py
- upsert command 
- Rename DocumentIndex to Record
> ENG-1393: Index improvements

- aixplain/modules/agent/__init__.py
- aixplain/modules/agent/tool/__init__.py
- aixplain/modules/agent/tool/model_tool.py
- aixplain/modules/agent/tool/pipeline_tool.py
- tests/unit/agent_test.py
> BUG-329: Fix agent validation when using api key

- .github/workflows/main.yaml
- .github/workflows/test.yaml
- pyproject.toml
- Run all unit tests at the start of workflow.
- Sync test.yaml workflow with the one on the main branch.
> ENG-1851: Update test and main workflows to run unit tests

- .github/workflows/main.yaml
This fix prevents all tests to fail when any of them fails.
> ENG-1852: Hotfix, added fail-fast option

- tests/unit/agent/agent_test.py
- tests/unit/team_agent/team_agent_test.py
Fixed `agent` and `team_agents` unit tests. Added update and save tests for `team_agents`.
Found a bug in both test files. "role" had to be renamed to "instructions" in all instances of both test files.
> Update unit tests for team-agents and agents

- aixplain/factories/agent_factory/__init__.py
- aixplain/factories/agent_factory/utils.py
- aixplain/factories/team_agent_factory/__init__.py
- aixplain/factories/team_agent_factory/utils.py
- aixplain/modules/agent/__init__.py
- aixplain/modules/agent/tool/model_tool.py
- aixplain/modules/team_agent/__init__.py
- aixplain/utils/llm_utils.py
- aixplain/v2/agent.py
> Update pyproject.toml (#659)
