README.md
aixtend/modules/model.py
aixtend/modules/pipeline.py

https://aixplain.monday.com/boards/3398410266/pulses/3416232401

Reformat output

---

.env.example
aixplain/utils/config.py

add python-dotenv load function to get envvar from .env file

add python-dotenv

---

README.md
docs/user/user_doc.md

modify the readme to show that it's possible to use URL or file path instead of typing the text directly as a string

modify the read me

---

README.md

The prior model used was Modern MT's translation model. We have changed it to an in-house model, NVidia English to French.

Update usage sample's model to an in-house model

---

aixplain/factories/file_factory.py

Add application file type (check [here](https://pypi.org/project/filetype/) for all supported types) with a 25MB limit and unrecognized file types with a 50MB limit.
Task: M-4629487375

Fix upload size limits

---

README.md

Add FineTune to README

---

docs/user/user_doc.md

Add supported tasks for FineTune in user documentation

---

aixplain/factories/dataset_factory.py
aixplain/utils/file_utils.py
docs/user/user_doc.md

adding the option to get the data from s3 url
converting the s3 url to a csv file

 converting s3 link to csv

---

aixplain/enums/__init__.py
aixplain/enums/function.py
aixplain/factories/dataset_factory.py
aixplain/utils/file_utils.py
aixplain/utils/validation_utils.py

the output can be done as well the issue is that the backend doesn't send the output datatype, so I want to suggest to modify the backend endpoint which send the functions and include the output datatype. we can discuss this further during the meeting

validating input of dataset onboarding

---

tests/functional/finetune/data/finetune_test_list_data.json
tests/functional/finetune/data/finetune_test_run_data.json
tests/functional/finetune/finetune_functional_test.py
tests/unit/finetune_test.py

Fix Finetuner unit and functional tests

---

aixplain/enums/__init__.py
aixplain/enums/supplier.py
aixplain/factories/model_factory.py
tests/functional/general_assets/asset_functional_test.py

- adding enum for suppliers
-  adding filter for suppliers
- fix issue which previous wasn't passing the json body to the request
- added test for the new feature "filtering with supplier/s"

Supplier Filter

---

tests/functional/finetune/data/finetune_test_run_data.json

Added fine-tuning Azure ASR functional test and it is working correctly.
Task: M-5165903341

Add Azure ASR fine-tuning to functional tests

---

aixplain/factories/model_factory.py
tests/unit/finetune_test.py

In ModelFactory list method:
- Renamed `functions` to `function` parameter.
- Updated `filter_params` not to use string values.
- Updated FineTune unit test to mock new endpoint from the backend.
Task: M-5263087343, M-5267676901 and M-5267256945

Fix ModelFactory list method

---

docs/user/user_doc.md

Updated Docker login and `create image-repo` commands in documentation.

Updated user doc for onboarding SDK

---

tests/functional/finetune/data/finetune_test_end2end.json

Update test end2end data in FineTune functional tests

---

tests/functional/finetune/data/finetune_test_cost_estimation.json
tests/functional/finetune/data/finetune_test_prompt_validator.json
tests/functional/finetune/finetune_functional_test.py

Update Finetuner functional tests

---

aixplain/modules/finetune/hyperparameters.py
tests/functional/finetune/data/finetune_test_cost_estimation.json
tests/functional/finetune/data/finetune_test_end2end.json
tests/functional/finetune/finetune_functional_test.py
tests/unit/finetune_test.py
tests/unit/hyperparameters_test.py

Update FineTune unit and functional tests

---

tests/functional/finetune/data/finetune_test_end2end.json
tests/functional/finetune/finetune_functional_test.py

Update Finetuner search metadata functional tests

---

pyproject.toml

Update click dependency

---

tests/functional/agent/agent_functional_test.py
tests/functional/team_agent/team_agent_functional_test.py

Add get method to agent and team agent tests

---

aixplain/modules/__init__.py
aixplain/modules/api_key.py
tests/functional/apikey/test_api.py

Get usage limit of an API key.

Get usage limit

---

aixplain/factories/api_key_factory.py
aixplain/modules/api_key.py
pyproject.toml
tests/functional/apikey/test_api.py

Make the update API Key functionality to work.

Fix Update API Key Bug

---

aixplain/factories/file_factory.py

Fix check_storage_type to not detect folder as a file

---

aixplain/modules/agent/tool/model_tool.py
tests/unit/agent_test.py

Add restriction when setting Utilities function in model tool

---

aixplain/factories/agent_factory/utils.py
aixplain/factories/pipeline_factory/utils.py
aixplain/modules/pipeline/asset.py
aixplain/modules/team_agent/__init__.py
tests/functional/pipelines/create_test.py
tests/functional/team_agent/team_agent_functional_test.py
tests/unit/pipeline_test.py
tests/unit/team_agent_test.py

Fixing the issue of deploying team agents and enabling the deployment of pipelines.

BUG-275: team deployment

---

aixplain/modules/agent/__init__.py
aixplain/modules/team_agent/__init__.py
tests/unit/agent_test.py
tests/unit/team_agent_test.py

Agent name validation to accept hyphens and brackets.

ENG-1422 validation

---

aixplain/v2/api_key.py
aixplain/v2/core.py
aixplain/v2/corpus.py
aixplain/v2/data.py
aixplain/v2/dataset.py
aixplain/v2/finetune.py
aixplain/v2/wallet.py

Assets:
- api key
- corpus
- data
- dataset
- wallet

ENG-1440: refactoring factories to aiXplain SDK v2

---

aixplain/modules/agent/tool/custom_python_code_tool.py
aixplain/modules/model/utils.py
tests/unit/agent_test.py

BUG-367: Fix CustomPythonCodeTool and add tests

---

aixplain/v2/benchmark.py

Update return type so it works with python 3.8 (#390)

Dev 2 Test

---

aixplain/modules/model/utils.py
tests/unit/utility_test.py

- Raise Error when  Utility Model `code` input is a Class object 
- Bug in parsing code string when output notation added `->` <Type> in fucntion

Utility model bulk bugs

---

aixplain/factories/team_agent_factory/__init__.py
aixplain/factories/team_agent_factory/utils.py
aixplain/modules/team_agent/__init__.py
tests/functional/team_agent/team_agent_functional_test.py
tests/unit/team_agent_test.py

ENG-1734: Add new inspector arguments

---

aixplain/enums/__init__.py
aixplain/modules/model/utility_model.py
tests/functional/model/run_utility_model_test.py
tests/unit/utility_test.py

- integrated with backend
- lifecycle of utilities are same as agents
- added test methods for status check and overwriting draft utility

ENG-1842: Utility asset status set to draft as default

---

tests/functional/team_agent/data/team_agent_test_end2end.json
tests/functional/team_agent/team_agent_functional_test.py

Revert "Team agent functional tests fix"

---

aixplain/factories/agent_factory/__init__.py
aixplain/modules/agent/tool/model_tool.py
aixplain/modules/agent/tool/python_interpreter_tool.py
tests/functional/agent/agent_functional_test.py
tests/unit/agent/agent_test.py
tests/unit/agent/model_tool_test.py

Model tool descriptions won't be sent as empty string anymore.

ENG-1830: Setting default tool description

---

aixplain/factories/agent_factory/utils.py
tests/unit/agent/agent_factory_utils_test.py

- Add unit tests for `agent_factory/utils.py`.

BUG-377: Handle case when agent function is none

---

.github/workflows/main.yaml

Task names abbreviated along with timeout adjustments for both globally and individually

Eng 2051 Improvements on CI flow

---

aixplain/enums/embedding_model.py
tests/functional/model/run_model_test.py

Adding a fine tuned version of the BGE modelo to aiR.

Add a finetuned version of BGE model

---

aixplain/modules/model/integration.py

1. **Bug Resolution & Testing**:
* Thoroughly tested authentication, data flow, and action execution for all connectors.
* Covered edge cases including incorrect credentials and unsupported schemas.
2. **Authentication Method Support**:
* **Added missing authentication methods**:
* `AuthenticationSchema.BASIC`
* `AuthenticationSchema.API_KEY`
* All supported schemas now:
```python
[
AuthenticationSchema.BEARER_TOKEN,
AuthenticationSchema.OAUTH1,
AuthenticationSchema.OAUTH2,
AuthenticationSchema.API_KEY,
AuthenticationSchema.BASIC,
AuthenticationSchema.NO_AUTH
]
```
3. **Dynamic Schema Retrieval & Validation**:
* Re-implemented `integration.py` to allow the SDK to:
* Dynamically fetch the supported authentication methods per integration.
* Raise precise errors when the wrong schema or …

Re-implement the integration.py file

---

aixplain/factories/model_factory/utils.py
aixplain/factories/tool_factory.py
tests/functional/agent/agent_functional_test.py
tests/functional/team_agent/team_agent_functional_test.py

Fixed a bug that `attributes` not being passed.
Added support to use integrations using ToolFactory.
Updated the tests with the correct asset ids, and action codes.

Eng 2400 add tests, fix composio bugs

---

tests/unit/model_test.py

Fixed the tests below, and updated them to be compatible with the new integration.py implementation.
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html  =========================== short test summary info ============================ FAILED tests/unit/model_test.py::test_create_model_from_response[payload0-Integration] - TypeError: 'NoneType' object is not iterable FAILED tests/unit/model_test.py::test_connector_connect[AuthenticationSchema.BEARER_TOKEN-test-name-test-token-None-None] - KeyError: 'attributes' FAILED tests/unit/model_test.py::test_connector_connect[AuthenticationSchema.OAUTH2-test-name-None-test-client-id-test-client-secret] - KeyError: 'attributes' FAILED tests/unit/model_test.py::test_tool_factory - KeyError: 'attributes' ============ 4 failed, 298 …

Fix integration tests in model_test.py
